### ISSUE TITLE
ODBCConnections.cls Could not understand line 165.

### ISSUE THREAD

**Issue by Jimbobnz** [PeterJudge-PSC/abl_odbc_api#1]
I believe that there might be bug in your code which is using the LENGTH() function to return the size of the MEMPTR. I do believe (unless the documentation is wrong) that this will only work for RAW, CHARACTER, LONGCHAR, CLOB & BLOB field and not MEMPTR. I unless I'm mistaken is the function you need to return the size of the MEMPTR, GET-SIZE()?

Current Code:
iValueLength = length(mValue).

Change to this:
iValueLength = get-size(mValue).

**Comment by PeterJudgeZA** [comment]
You're right - GET-SIZE() should be used.

**Comment by PeterJudgeZA** [comment]
Fixed in  65a465ed8034fdb638d79ea0fbcca14c421abef2
