### ISSUE TITLE
How do I make this code work with OpenEdge 11.6

### ISSUE THREAD

**Issue by Jimbobnz** [PeterJudge-PSC/abl_odbc_api#2]
Since EmumMember.cls file has been excluded from OpenEdge.Core.pl procedure libary, how or what do I need to change to make the code work with OE 11.6. 

I do believe that EmumMember was introduced in OE 11.6. So I'm not sure what I need to do to adopt the new methodology.

**Comment by PeterJudgeZA** [comment]
change all of the *Enum.cls files from
CLASS FooEnum INHERITS EnumMember:
to ENUM FooEnum:

You'll also need to change the lines that look like 
{Consultingwerk/EnumMember.i SQL_C_CHAR SqlTypeEnum:SQL_CHAR:Value CTypeEnum}.

to use the new DEFINE ENUM syntax.

**Comment by Jimbobnz** [comment]
Thanks for this. I think what I will do for the interim is extract the EmumMember.cls class file from version 11.5 and place it located in my propath. I don't have the confidence to undertake a major code change yet.

**Comment by PeterJudgeZA** [comment]
Followed your approach and added EnumMember and FlagsEnum to the codebase. Fixed in 65a465ed8034fdb638d79ea0fbcca14c421abef2
